name: CD Edge

on:
  push:
    branches:
    - 'master'

jobs:

  build-image:

    runs-on: ubuntu-latest

    steps:

    - name: Repository Checkout
      uses: actions/checkout@v2

    - name: Docker Build
      run: |
        docker build . \
          --build-arg VERSION=$(git describe --tags --abbrev=0) \
          -t evolvedpacks/evi:edge \
          -f .docker/Dockerfile

    - name: Docker Push
      run: |
        docker login -u zekro -p ${{ secrets.DOCKER_PASSWORD }}
        docker push evolvedpacks/evi:edge